### ISSUE TITLE
Get participants by graph ID

### ISSUE THREAD

**Issue by djvill** [nzilbb/labbcat-R#16]
Currently, `getGraphIdsWithParticipant()` allows the user to find all graphs associated with a certain participant, but the inverse operation, finding all participants associated with a certain graph, is only possible through running `getGraphIdsWithParticipant()` on the full list of participants. Ideally, there would be a function `getParticipantsInGraphId()` that would perform the inverse operation.

**Comment by robertfromont** [comment]
Thinking about this, I'm hoping it can be the case that, for any given information about a transcript, you can get that information by querying for annotations within the transcript itself, using `getAnnotations`.

Mostly annotations in a graph (i.e. a transcript) are either things that label a portion of time, or things that label other annotations.  However, some annotations are 'about' the whole transcript - e.g. transcript attributes like the main language, the transcriber's name, etc. These 'whole transcript' annotations actually include annotations that represent the participants, on a layer called 'participant'.

So the idea is that, to get a list of participants in a transcript, you could do something like:
```
participants <- getAnnotations(labbcat.url, transcriptName, "participant")
participantNames <- participants$label
```

This doesn't work on current released versions, for a couple of reasons:

- The layer is currently called 'who', instead of 'participant' (but that's about to change)
- Even if you try to get "who"-layer annotations, you get an error because that layer is 'special' and not supported for querying in the currently-available version of LaBB-CAT (but that's about to change)

However, it *will* work as of version 0.5-1
